name: amp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  file_picker: ^10.3.10
  flutter:
    sdk: flutter
  m3e_collection: ^0.3.7
  meta: ^1.17.0
  navigation_rail_m3e: ^0.3.5
  rinf: ^8.10.0
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
